

const data = {
    products: [
        {
            _id: '1',
            category:['Shirts','Top','New'],
            countInsStock: 0,
            brand:'Zara',
            rating:4.5,
            numReview:15,
            name: 'Puff-Sleeve Round-Neck Blouse',
            description: 'high quality product',
            img: '/Images/products/woman/product_1.png',
            price: 1300,
        },
        {
            _id: '2',
            category:['Shirts','Top','New'],
            countInsStock: 10,
            brand:'Zara',
            rating:4.5,
            numReview:15,
            name: 'Drawstring Frilled Lace Blouse',
            description: 'high quality product',
            img: '/Images/products/woman/product_2.png',
            price: 1830,
        },
        {
            _id: '3',
            category:['Shirts','Top','New'],
            countInsStock: 10,
            brand:'Zara',
            rating:4.5,
            numReview:15,
            name: 'Frilled Layered-Collar Blouse',
            description: 'high quality product',
            img: '/Images/products/woman/product_3.png',
            price: 3200,
        },
        {
            _id: '4',
            category:['Shirts','Top','New'],
            countInsStock: 10,
            brand:'Zara',
            rating:4.5,
            numReview:15,
            name: 'Colored Loose-Fit Knit Top',
            description: 'high quality product',
            img: '/Images/products/woman/product_4.png',
            price: 1854.67,
        },
        {
            _id: '5',
            category:['Shirts','Top','New'],
            countInsStock: 10,
            brand:'Zara',
            rating:4.5,
            numReview:15,
            name: 'Brushed Fleece Lined T-Shirt',
            description: 'high quality product',
            img: '/Images/products/woman/product_5.png',
            price: 1854.67,
        },
        {
            _id: '6',
            category:['Shirts','Top','New'],
            countInsStock: 10,
            brand:'Zara',
            rating:4.5,
            numReview:15,
            name: 'Ruffle Trim Long-Sleeve Blouse',
            description: 'high quality product',
            img: '/Images/products/woman/product_6.png',
            price: 1050.59,
        },
        {
            _id: '7',
            category:['Shirts','Top','New'],
            countInsStock: 10,
            brand:'Zara',
            rating:4.5,
            numReview:15,
            name: 'Contrast Black Trim Long-Sleeve T-Shirt',
            description: 'high quality product',
            img: '/Images/products/woman/product_7.png',
            price: 1050.59,
        },
    ]
}

export default data;